export const RETRIEVE_COVID_STATUS_BEGIN = 'RETRIEVE_COVID_STATUS_BEGIN';
export const RETRIEVE_COVID_STATUS_SUCCESS = 'RETRIEVE_COVID_STATUS_SUCCESS';
export const RETRIEVE_COVID_STATUS_FAILURE = 'RETRIEVE_COVID_STATUS_SUCCESS';
